# Generated by Django 3.2 on 2021-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cetagory',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='articles',
            name='sub_cetagory',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
