# Generated by Django 3.2 on 2021-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211203_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
