# Generated by Django 3.2 on 2022-01-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='total_articles_length',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
