# Generated by Django 3.2 on 2022-01-08 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_savedarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedarticles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viewarticlehistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
