# Generated by Django 3.2 on 2022-01-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Replay',
            new_name='replay',
        ),
    ]
