# Generated by Django 3.2 on 2022-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_replay_contact_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='replay',
            field=models.TextField(blank=True, default=''),
        ),
    ]
