# Generated by Django 3.2 on 2022-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_contact_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
