# Generated by Django 3.2 on 2022-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_contact_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='seen',
            new_name='seen_by_manager',
        ),
        migrations.AddField(
            model_name='contact',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
