# Generated by Django 3.2 on 2022-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Replay_Comment',
            field=models.TextField(blank=True),
        ),
    ]
