# Generated by Django 3.2 on 2022-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20220118_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay_comment',
            name='UserName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
