# Generated by Django 3.2 on 2022-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_replay_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
