# Generated by Django 3.2 on 2022-01-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='replay_comment',
            name='UserName',
        ),
    ]
