# Generated by Django 3.2 on 2022-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20220121_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay_comment',
            old_name='replay_comment',
            new_name='replay_comment_text',
        ),
        migrations.RemoveField(
            model_name='replay_comment',
            name='User',
        ),
        migrations.RemoveField(
            model_name='replay_comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='replay_comment',
            field=models.ManyToManyField(to='articles.Replay_Comment'),
        ),
    ]
