# Generated by Django 3.2 on 2022-01-21 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0022_auto_20220121_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replay_comment',
        ),
        migrations.AddField(
            model_name='replay_comment',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replay_comment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
            preserve_default=False,
        ),
    ]
