# Generated by Django 3.2 on 2022-01-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20220122_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay_comment_text',
            field=models.TextField(blank=True),
        ),
    ]
