# Generated by Django 3.2 on 2022-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_remove_comment_replay_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay_comment_text',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
