# Generated by Django 3.2 on 2022-01-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_comment_replay_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay_Comment',
        ),
    ]
